repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict
          - id: check-added-large-files
          - id: check-ast
          - id: check-symlinks
          - id: trailing-whitespace
          - id: check-json
          - id: debug-statements
          - id: check-toml
          - id: check-yaml
            exclude: mkdocs.yml
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          name: isort (python)
        - id: isort
          name: isort (cython)
          types: [cython]
        - id: isort
          name: isort (pyi)
          types: [pyi]
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.241
      hooks:
          - id: ruff
            args:
              - --fix
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
            args: ["--target-version", "py39"]
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py37-plus]

