ignore:
  - "authx/core/config.py"
  - "authx/main.py"
  - "authx/utils/**"
  - "authx/errors/**"
  - "authx/database/**"
  - "authx/cache/**"
  - "authx/services/**"
  - "tests/middleware/example/**"