site_name: AuthenticationX
site_description: Ready to use and customizable Authentications and Oauth2 management for FastAPI ⚡
site_url: https://authx.yezz.me/

theme:
  features:
    - header.autohide
  name: 'material'
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  favicon: favicon.png
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github
repo_name: Yezz123/AuthX
repo_url: https://github.com/yezz123/AuthX
edit_uri: ""

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tasklist
  - pymdownx.tabbed

plugins:
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - About: index.md
  - installation.md
  - configuration/Get-Started.md
  - Configuration:
    - Models:
      - Introduction: configuration/models/index.md
      - configuration/models/base.md
      - configuration/models/social.md
      - configuration/models/properties.md
    - Database:
      - Introduction: configuration/database/index.md
      - configuration/database/encodedb.md
      - configuration/database/mongodb.md
    - Cache:
      - Introduction: configuration/cache/index.md
      - configuration/cache/redis.md
      - configuration/cache/HTTPCache.md
      - configuration/cache/Example.md
    - Security:
      - Introduction: configuration/security/index.md
      - configuration/security/jwt.md
      - configuration/security/session.md
      - configuration/security/email.md
      - configuration/security/captcha.md
      - configuration/security/hashing.md
    - Operations:
      - Introduction: configuration/crud/index.md
    - Services:
      - Introduction: configuration/services/index.md
      - configuration/services/authentication.md
      - configuration/services/admin.md
      - configuration/services/password.md
      - configuration/services/social-authentication.md
      - configuration/services/search.md
    - Routers:
      - Introduction: configuration/routers/index.md
      - configuration/routers/authentication.md
      - configuration/routers/admin.md
      - configuration/routers/password.md
      - configuration/routers/social.md
      - configuration/routers/search.md
    - Middleware:
      - Introduction: configuration/middleware/index.md
      - configuration/middleware/service-performance.md
      - configuration/middleware/example.md
      - configuration/middleware/profiling.md
    - Socket:
      - Introduction: configuration/socket/index.md
  - Help AuthX - Get Help: help.md
  - Development - Contributing: contributing.md
  - Frequently Asked Questions: faq.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md
  - Release Notes: release.md

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/yezz123
  - icon: fontawesome/brands/discord
    link: https://discord.gg/2hdSWVgNPH
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/THyasser1
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/yezz123
  - icon: fontawesome/solid/globe
    link: https://yezz.me
  - icon: fontawesome/brands/product-hunt
    link: https://producthunt.com/posts/authx
