[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "authx"
description = "Ready to use and customizable Authentications and Oauth2 management for FastAPI"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Yasser Tahiri", email = "hello@yezz.me" },
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Framework :: FastAPI",
    "Framework :: AsyncIO",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Internet :: WWW/HTTP :: Session",
    "Typing :: Typed",
]

dependencies = [
    "fastapi >=0.65.2,<0.90.0",
    "passlib ==1.7.4",
    "bcrypt ==4.0.1",
    "email-validator >=1.1.0,<1.3.1",
    "pyjwt ==2.6.0",
    "cryptography==39.0.0",
    "httpx==0.23.3",
    "itsdangerous == 2.1.2",
    "aiosmtplib == 2.0.1",
    "pydantic==1.10.4",
    "databases == 0.7.0",
    "motor == 3.1.1",
    "Authlib==0.15.5",
    "starlette >=0.14.02,<0.23.2",
    "aioredis >=2.0.1,<2.1.0",
    "redis >=4.3.3,<4.4.2",
    "pytz==2022.7",
    "python-dateutil==2.8.2",
    "python-socketio >=4.6.0,<5.7.3",
    "pyinstrument >=4.1.1,<4.5.0",
    "SQLAlchemy >=1.4.37,<1.4.47",
    "prometheus-client",
]

dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/yezz123/authx"
Documentation = "https://authx.yezz.me/"
Funding = 'https://github.com/sponsors/yezz123'

[project.optional-dependencies]
lint = [
    "pre-commit==2.21.0",
]
test = [
    "pytest==7.2.0",
    "pytest-asyncio == 0.20.3",
    "requests==2.28.1",
    "uvicorn==0.20.0",
    "asynctest==0.13.0",
    "codecov==2.1.12",
    "pytest-cov==4.0.0",
    "websockets==10.4",
    "uvloop==0.17.0"
]
docs = [
    "mkdocs >=1.1.2,<2.0.0",
    "mkdocs-material >=8.1.4,<10.0.0",
    "mdx-include >=1.4.1,<2.0.0",
    "mkdocs-markdownextradata-plugin >=0.1.7,<0.3.0",
    "mkdocs-mermaid2-plugin==0.6.0",
    "markdown-include==0.8.0",
    "pymdown-extensions==9.9",
    "jinja2==3.1.2"
]

[tool.hatch.version]
path = "authx/__init__.py"
