[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "authx"
dist-name = "authx"
author = "Yasser Tahiri"
author-email = "yasserth19@gmail.com"
home-page = "https://github.com/yezz123/authx"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Framework :: FastAPI",
    "Framework :: AsyncIO",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Internet :: WWW/HTTP :: Session",
    "Typing :: Typed",
]
description-file = "README.md"
requires-python = ">=3.8"
requires = [
    "fastapi >=0.65.2,<0.78.0",
    "passlib ==1.7.4",
    "bcrypt ==3.2.2",
    "email-validator >=1.1.0,<1.2.1",
    "pyjwt ==2.4.0",
    "cryptography==37.0.2",
    "httpx==0.23.0",
    "itsdangerous == 2.1.2",
    "aiosmtplib == 1.1.6",
    "pydantic==1.9.1",
    "databases == 0.6.0",
    "motor == 3.0.0",
    "Authlib==0.15.5",
    "starlette >=0.14.02,<0.20.1",
    "aioredis >=2.0.1,<2.1.0",
    "redis==4.3.3",
    "pytz==2022.1",
    "python-dateutil==2.8.2",
    "python-socketio>=4.6.0"
]

[tool.flit.metadata.requires-extra]
lint = [
    "pre-commit==2.19.0",
]
test = [
    "pytest==7.1.2",
    "pytest-asyncio == 0.18.3",
    "requests==2.27.1",
    "uvicorn==0.17.6",
    "asynctest==0.13.0",
    "codecov==2.1.12",
    "pytest-cov==3.0.0",
    "SQLAlchemy==1.4.37",
    "uvloop==0.16.0",
    "websockets==10.3"
]
docs = [
    "mkdocs >=1.1.2,<2.0.0",
    "mkdocs-material >=8.1.4,<9.0.0",
    "mdx-include >=1.4.1,<2.0.0",
    "mkdocs-markdownextradata-plugin >=0.1.7,<0.3.0",
    "mkdocs-mermaid2-plugin==0.5.2",
    "markdown-include==0.6.0",
    "pymdown-extensions==9.1",
    "jinja2==3.0.3"
]

[tool.flit.metadata.urls]
Documentation = "https://authx.yezz.me/"