version: "3.3"
services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.sample
    image: authx
