name: Docker tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: pull latest
        run: docker-compose pull
      - name: Build image
        run: docker-compose build
      - name: Test image
        run: docker-compose run --rm authx pytest --cov=authx/ --cov-report=html
