name: Local Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.version }}
    strategy:
      matrix:
        version: [3.8,3.9,3.10.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.dev.txt
      - name: Test Project
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          python -m pytest --cov=AuthX/ --cov-report=html
          codecov
